name: Workflow
on: [push, pull_request]

jobs:
  filter-changed-packages:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Filter changed packages
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changed:
              - 'packages/react/src/hooks/**'
      - name: Set matrix
        id: set-matrix
        run: |
          if [[ "${{ steps.filter.outputs.changes }}" == "[]" ]]; then
          echo "::set-output name=matrix::[]"
          else
          echo "::set-output name=matrix::[\"react\"]"
          fi
  run:
    runs-on: ubuntu-latest
    needs: filter-changed-packages
    strategy:
      matrix:
        package: ${{fromJson(needs.filter-changed-packages.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: cd packages/${{matrix.package}} && yarn install
      - name: Run tests and collect coverage
        continue-on-error: true
        run: cd packages/${{matrix.package}} && yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
